# Generated by Django 3.2.7 on 2021-09-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_before',
            field=models.IntegerField(null=True),
        ),
    ]
