# Generated by Django 3.2.7 on 2021-10-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211018_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Super', 'Super'), ('Regular', 'Regular')], default='Regular', max_length=100),
        ),
    ]
