# Generated by Django 3.2.7 on 2021-10-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211013_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
