# Generated by Django 3.2.7 on 2021-09-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_alert_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='alert_before',
            new_name='alert_if_lower_than',
        ),
    ]
