# Generated by Django 3.2.7 on 2021-10-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211002_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('payed', models.FloatField()),
                ('expected_earn', models.FloatField()),
                ('earn', models.FloatField()),
                ('dept', models.FloatField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.currency')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.seller')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('piece_price', models.FloatField()),
                ('total', models.FloatField()),
                ('product', models.ManyToManyField(to='product.Invoice')),
            ],
        ),
    ]
