# Generated by Django 3.2.7 on 2021-09-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_alert_before_product_alert_if_lower_than'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(null=True, to='product.Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.quantitytype'),
        ),
    ]
