# Generated by Django 3.2.7 on 2021-09-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210919_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(to='product.Material'),
        ),
    ]
