# Generated by Django 3.2.7 on 2021-10-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_invoicepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepayment',
            name='invoice',
        ),
    ]
