# Generated by Django 3.2.7 on 2021-10-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_invoicepayment_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicepayment',
            old_name='Currency',
            new_name='currency',
        ),
    ]
