# Generated by Django 3.2.7 on 2021-10-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_currency_invoicepayment_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBoxOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('operation', models.CharField(choices=[('1', 'Add'), ('2', 'Take')], max_length=5)),
                ('reason', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.currency')),
            ],
        ),
    ]
