# Generated by Django 3.2.7 on 2021-10-18 10:37
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0009_dailyboxoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyboxoperation',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
