# Generated by Django 3.2.7 on 2021-10-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20211018_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyBoxOperation',
        ),
    ]
