# Generated by Django 3.2.7 on 2021-10-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_dailyboxoperation_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyboxoperation',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
